
# html lang
language: zh-cn

# main menu navigation
menu:
  Home: /
  Archives: archives
  Tags: tags
  Categories: categories
  About: about

social:
  GitHub: https://github.com/songjinzhong

# Miscelaneous
favicon: images/favicon.ico

# categories that important
categories:
- JavaScript

# stylesheets loaded in the <head>
stylesheets:
- /css/all.min.css

# scripts loaded in the end of the body
scripts:
- /js/jquery-3.1.0.min.js
- /js/all.min.js

# duoshuo name
duoshuo: yurenspace

# github-url
github: https://github.com/songjinzhong

# weibo-url
weibo: http://weibo.com/songjinz

# me.png
me: /images/me.png

# baidu_tongji
baidu_tongji: 513bc3e28555252418b03cc8e660bc31

# google_tongji
google_tongji: UA-85346637-1

# zhanzhang_tongji
zhanzhang_tongji: 1260592860