<script type="text/javascript">
  var cnzz_s_tag = document.createElement('script');
  cnzz_s_tag.type = 'text/javascript';
  cnzz_s_tag.async = true;
  cnzz_s_tag.charset = 'utf-8';
  cnzz_s_tag.src = 'https://w.cnzz.com/c.php?id={{config.zhanzhang_tongji||theme.zhanzhang_tongji}}&web_id={{config.zhanzhang_tongji||theme.zhanzhang_tongji}}';
  var root_s = document.getElementsByTagName('script')[0];
  root_s.parentNode.insertBefore(cnzz_s_tag, root_s);
</script>